# Generated by Django 5.0.3 on 2024-04-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_mentoring_language_customuser_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profile_image',
        ),
    ]
